# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-13 11:16
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=40)),
                ('age', models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(75)])),
                ('country', models.CharField(default=b'USA', max_length=30)),
                ('height', models.FloatField(default=1.3, validators=[django.core.validators.MaxValueValidator(2.2)])),
                ('photo', models.ImageField(upload_to=b'artist/')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=15)),
                ('year', models.DateField(default=datetime.date(2017, 1, 1))),
                ('song_toupload', models.FileField(upload_to=b'songs/')),
                ('song_cover', models.ImageField(upload_to=b'songs_cover/')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbeats.Artist')),
            ],
        ),
    ]
